### PR TITLE
Alerting email improvements

### PR DESCRIPTION
**Pull request by mattttt**
Addressing Issue: https://github.com/raintank/grafana/issues/279

### CODE REVIEW

**Comment by Dieterbe** [comment]
instead of saying "False alert? You can adjust your settings in your config" can we make that a link that brings them straight to the monitoring config for the given endpoint and check type?

**Comment by mattttt** [comment]
Yep, would like to do that - I'll pop a second ticket to extend the variables I have available to me. I only have the endpoint slug available, and I need the endpoint ID to construct the link.

That said, this issue needs to be resolved first anyway: https://github.com/raintank/grafana/issues/287

**Comment by mattttt** [comment]
What do you guys think of a change in the design:
screenshot 2015-07-03 11 52 43
screenshot 2015-07-03 11 52 38

(Quick and dirty - in real life, the edges of the hearts wont be clipped)

**Comment by Dieterbe** [comment]
I think it looks good.
though those slugified endpoints are still a thorn in my eye.
we should have a variable that contains the *true* endpoint ("www.my_website.com")

**Comment by bulletfactory** [comment]
Nice- the colored heading works well.
T

**Pull request merged**
