### PR TITLE
New collector page (needs wiring)

### PR DESCRIPTION
**Pull request by mattttt**
This is almost complete, but needs some wiring up with angular. Can you help with this over the next couple days? I'd like to have it merged this week.

### CODE REVIEW

**Comment by mattttt** [comment]
(not ready to merge yet)

**Comment by mattttt** [comment]
@woodsaj Think we can work on this in the next couple days? Thanks!

**Comment by woodsaj** [comment]
@mattttt wired up the page.

I added the handling of the "verify install" button to wait for the collector to come online.  Though the messaging needs UI work.

https://github.com/raintank/grafana/blob/nchristus-new-collector-page/public/plugins/raintank/features/partials/collectors_new.html#L130-L137

**Comment by mattttt** [comment]
Excellent, will get this turned around and pushed into master.

**Comment by mattttt** [comment]
This looks good from my side. All you, @woodsaj

**Pull request merged**
