### PR TITLE
Litmus alerting v3

### PR DESCRIPTION
**Pull request by Dieterbe**
culmination of alerting work so far.
I want to spend some time this week validating core logic, verifying performance, and making sure things are in good shape to be merged before I go on vacation.
i will be adding statsd instrumentation and will potentially change some things, but I wanted to give @woodsaj and @torkelo some heads up so you can start looking already.  This is my 4th rebase or so, so hopefully it can be merged soonish.

notably missing:
1. UI and logic to save/manage health/alerting settings, see #110 
2. doing useful things with results of monitoring checks.

maybe i can get something done on those this week, maybe not.  I rather make sure the core alerting stuff works well as the missing stuff is something that could fairly easily be added by somebody else. (hopefully @woodsaj has some time)

We should also discuss what number 2 will entail.  I remember @nopzor1200 saying emailing was secondary for monitorama and first step would be just logging the events and viewing them, it would be nice to get emailing done though. but this requires some more discussion since @woodsaj has a clearer view on how the "health handling" could fit in with the current code base.

### CODE REVIEW

**Comment by Dieterbe** [comment]
oh yes, since most of this PR is in Godeps (pulling in bosun), I found I can simply run go diff on main.go and the pkg directory to see all "real" changes.

**Comment by torkelo** [comment]
Looks good. 

Just a thinking ahead (maybe not top prio right now as we just want something simple to work for public beta), I am not sure how this can be distributed into multiple producer and consumer processes. Will need some kind of lock/sync table to generate work. The duplicate work check work will not work in a distributed setup right? unless we have some distributed cache.

**Comment by Dieterbe** [comment]
>  I am not sure how this can be distributed into multiple producer and consumer processes. Will need some kind of lock/sync table to generate work

we would use a standalone queue (looks like rabbit but we'll see) and the schedulers and executors can just be run as as is.  the schedulers would redundantly schedule jobs, jobs would be consistently routed by the queue based on their key, and the executors wouldn't execute jobs with keys they have already seen. so nothing else should be needed. I think slower graphite queries will probably become a bottleneck before the schedulers or executors.  but that's why i'm doing testing (performance and correctness) testing this week.

**Comment by Dieterbe** [comment]
added some more commits, updated tests, statsd metrics, dashboard, etc.

**Comment by mattttt** [comment]
The latest commit covers updates to the forms, and the addition of a separator at the bottom for the Update button. Previously it felt too tied to the Alerting section, and we want to make sure people understand it's update the whole check. 

This is only a first pass, we'll revise over time.

**Pull request merged**
