### PR TITLE
don't hardcode app url.  use what is set through the config

### LINKED ISSUE #456: alert emails from dev point to prod
emails from dev-hallo@ have a link to http://app.raintank.io
not sure if a bug in grafana or a mis configuration in dev?
@woodsaj @ctdk

### PR DESCRIPTION
**Pull request by Dieterbe**
fix #456

i basically just ran `codemod.py --extension html 'https://app.raintank.io/' '{{.AppUrl}}'`

with codemod from https://github.com/facebook/codemod/ (neat tool!)

@woodsaj looks good?

### CODE REVIEW

**Comment by Dieterbe** [comment]
@woodsaj ?

**Comment by woodsaj** [comment]
has this been tested?  We need to make sure that the emails render correctly in email clients.

**Comment by Dieterbe** [comment]
no, how can i test this besides running it in dev?

**Comment by ctdk** [comment]
You could run it locally and set up the smtp settings so it can send email. Either that, or we can just test it on dev-portal. That, ironically, is where the problem shows up.

**Comment by woodsaj** [comment]
@Dieterbe your devstack can send emails.  just configure the smtp settings in your grafana config.

**Comment by Dieterbe** [comment]
tested with:
* alert notification email
* reset password email

**Pull request merged**
